"""Unique mcp/a2a server url per user constraint

Revision ID: 8403bb364491
Revises: 046a06a0b0a4
Create Date: 2025-07-07 13:05:36.680696

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8403bb364491"
down_revision: Union[str, None] = "046a06a0b0a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("a2acards_server_url_key", "a2acards", type_="unique")
    op.create_unique_constraint(
        "uq_a2a_card_server_url", "a2acards", ["creator_id", "server_url"]
    )
    op.drop_constraint("mcpservers_server_url_key", "mcpservers", type_="unique")
    op.create_unique_constraint(
        "uq_mcp_server_url", "mcpservers", ["creator_id", "server_url"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_mcp_server_url", "mcpservers", type_="unique")
    op.create_unique_constraint(
        "mcpservers_server_url_key", "mcpservers", ["server_url"]
    )
    op.drop_constraint("uq_a2a_card_server_url", "a2acards", type_="unique")
    op.create_unique_constraint("a2acards_server_url_key", "a2acards", ["server_url"])
    # ### end Alembic commands ###
